const {Router} = require('express')
const {clienteRouters}= require('../routes/clienteRoutes')
const {categoriaRouters}= require('../routes/categoriaRoutes')
const {productoRouters}= require('../routes/productoRoutes')
const {pedidoDetalleRouters}= require('../routes/DetallePedidoRoutes')
const {empleadoRouters}= require('../routes/EmpleadoRoutes')
const {estadoPedidoRouters}= require('../routes/EstadoPedidoRoutes')
const {facturaRouters} = require('../routes/FacturaRoutes')
const {historialEstadoRouters} = require('../routes/HistorialEstadoRoutes')
const {pedidoRouters} = require('../routes/PedidoRoutes')
const {proyectoRouters} = require('../routes/proyectoRoutes')

const router= Router()
router.use('/clientes',clienteRouters)
router.use('/categorias',categoriaRouters)
router.use('/productos',productoRouters)
router.use('/pedidosDetalle',pedidoDetalleRouters)
router.use('/pedidosDetalle',pedidoRouters)
router.use('/empleado',empleadoRouters)
router.use('/estadoP',estadoPedidoRouters)
router.use('/factura',facturaRouters)
router.use('/historial',historialEstadoRouters)
router.use('/proyecto',proyectoRouters)

module.exports = router